# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

community_category = Category.where(name: 'community').first_or_create(name: 'community')
housing_category = Category.where(name: 'housing').first_or_create(name: 'housing')
forsale_category = Category.where(name: 'for sale').first_or_create(name: 'for sale')
gigs_category = Category.where(name: 'gigs').first_or_create(name: 'gigs')
personals_category = Category.where(name: 'personals').first_or_create(name: 'personals')
services_category = Category.where(name: 'services').first_or_create(name: 'services')
discussionforums_category = Category.where(name: 'discussion forum').first_or_create(name: 'discussion forum')
resumes_category = Category.where(name: 'resumes').first_or_create(name: 'resumes')

Subcategory.where(name: 'activities', category_id: community_category.id).first_or_create(name: 'activities', category_id: community_category.id)
Subcategory.where(name: 'classes', category_id: community_category.id).first_or_create(name: 'classes', category_id: community_category.id)
Subcategory.where(name: 'events', category_id: community_category.id).first_or_create(name: 'events', category_id: community_category.id)

Subcategory.where(name: 'apts/housing for rent', category_id: housing_category.id).first_or_create(name: 'apts/housing for rent', category_id: housing_category.id)
Subcategory.where(name: 'apts wanted', category_id: housing_category.id).first_or_create(name: 'apts wanted', category_id: housing_category.id)
Subcategory.where(name: 'housing swap', category_id: housing_category.id).first_or_create(name: 'housing swap', category_id: housing_category.id)
Subcategory.where(name: 'office & command', category_id: housing_category.id).first_or_create(name: 'office & command', category_id: housing_category.id)
Subcategory.where(name: 'parking & storage', category_id: housing_category.id).first_or_create(name: 'parking & storage', category_id: housing_category.id)
Subcategory.where(name: 'real estate -by broker', category_id: housing_category.id).first_or_create(name: 'real estate -by broker', category_id: housing_category.id)
Subcategory.where(name: 'real estate -by owner', category_id: housing_category.id).first_or_create(name: 'real estate -by owner', category_id: housing_category.id)
Subcategory.where(name: 'room & shares', category_id: housing_category.id).first_or_create(name: 'room & shares', category_id: housing_category.id)
Subcategory.where(name: 'rooms wanted', category_id: housing_category.id).first_or_create(name: 'rooms wanted', category_id: housing_category.id)
Subcategory.where(name: 'sublets & temporary', category_id: housing_category.id).first_or_create(name: 'sublets & temporary', category_id: housing_category.id)
Subcategory.where(name: 'sublet/temporary wanted', category_id: housing_category.id).first_or_create(name: 'sublet/temporary wanted', category_id: housing_category.id)
Subcategory.where(name: 'vacation renters', category_id: housing_category.id).first_or_create(name: 'vacation renters', category_id: housing_category.id)

Subcategory.where(name: 'antiques', category_id: forsale_category.id).first_or_create(name: 'antiques', category_id: forsale_category.id)
Subcategory.where(name: 'appliances', category_id: forsale_category.id).first_or_create(name: 'appliances', category_id: forsale_category.id)
Subcategory.where(name: 'arts+crafts', category_id: forsale_category.id).first_or_create(name: 'arts+crafts', category_id: forsale_category.id)
Subcategory.where(name: 'atv/utv/sno', category_id: forsale_category.id).first_or_create(name: 'atv/utv/sno', category_id: forsale_category.id)
Subcategory.where(name: 'auto parts', category_id: forsale_category.id).first_or_create(name: 'auto parts', category_id: forsale_category.id)
Subcategory.where(name: 'baby+kid', category_id: forsale_category.id).first_or_create(name: 'baby+kid', category_id: forsale_category.id)
Subcategory.where(name: 'barter', category_id: forsale_category.id).first_or_create(name: 'barter', category_id: forsale_category.id)
Subcategory.where(name: 'beauty+hlth', category_id: forsale_category.id).first_or_create(name: 'beauty+hlth', category_id: forsale_category.id)
Subcategory.where(name: 'bikes', category_id: forsale_category.id).first_or_create(name: 'bikes', category_id: forsale_category.id)
Subcategory.where(name: 'books', category_id: forsale_category.id).first_or_create(name: 'books', category_id: forsale_category.id)
Subcategory.where(name: 'business', category_id: forsale_category.id).first_or_create(name: 'business', category_id: forsale_category.id)
Subcategory.where(name: 'boats', category_id: forsale_category.id).first_or_create(name: 'boats', category_id: forsale_category.id)
Subcategory.where(name: 'business', category_id: forsale_category.id).first_or_create(name: 'business', category_id: forsale_category.id)
Subcategory.where(name: 'cars+trucks', category_id: forsale_category.id).first_or_create(name: 'cars+trucks', category_id: forsale_category.id)
Subcategory.where(name: 'cds/dvd/vhs', category_id: forsale_category.id).first_or_create(name: 'cds/dvd/vhs', category_id: forsale_category.id)
Subcategory.where(name: 'cell phones', category_id: forsale_category.id).first_or_create(name: 'cell phones', category_id: forsale_category.id)
Subcategory.where(name: 'collectibles', category_id: forsale_category.id).first_or_create(name: 'collectibles', category_id: forsale_category.id)
Subcategory.where(name: 'computers', category_id: forsale_category.id).first_or_create(name: 'computers', category_id: forsale_category.id)
Subcategory.where(name: 'electronices', category_id: forsale_category.id).first_or_create(name: 'electronices', category_id: forsale_category.id)
Subcategory.where(name: 'farm+garden', category_id: forsale_category.id).first_or_create(name: 'farm+garden', category_id: forsale_category.id)
Subcategory.where(name: 'free', category_id: forsale_category.id).first_or_create(name: 'free', category_id: forsale_category.id)
Subcategory.where(name: 'furniture', category_id: forsale_category.id).first_or_create(name: 'furniture', category_id: forsale_category.id)
Subcategory.where(name: 'garage sale', category_id: forsale_category.id).first_or_create(name: 'garage sale', category_id: forsale_category.id)
Subcategory.where(name: 'general', category_id: forsale_category.id).first_or_create(name: 'general', category_id: forsale_category.id)
Subcategory.where(name: 'heavy equip', category_id: forsale_category.id).first_or_create(name: 'heavy equip', category_id: forsale_category.id)
Subcategory.where(name: 'household', category_id: forsale_category.id).first_or_create(name: 'household', category_id: forsale_category.id)
Subcategory.where(name: 'jewelry', category_id: forsale_category.id).first_or_create(name: 'jewelry', category_id: forsale_category.id)
Subcategory.where(name: 'materials', category_id: forsale_category.id).first_or_create(name: 'materials', category_id: forsale_category.id)
Subcategory.where(name: 'motorcycles', category_id: forsale_category.id).first_or_create(name: 'motorcycles', category_id: forsale_category.id)
Subcategory.where(name: 'music instr', category_id: forsale_category.id).first_or_create(name: 'music instr', category_id: forsale_category.id)
Subcategory.where(name: 'photo+video', category_id: forsale_category.id).first_or_create(name: 'photo+video', category_id: forsale_category.id)
Subcategory.where(name: 'rvs+camp', category_id: forsale_category.id).first_or_create(name: 'rvs+camp', category_id: forsale_category.id)
Subcategory.where(name: 'sporting', category_id: forsale_category.id).first_or_create(name: 'sporting', category_id: forsale_category.id)
Subcategory.where(name: 'tickets', category_id: forsale_category.id).first_or_create(name: 'tickets', category_id: forsale_category.id)
Subcategory.where(name: 'tools', category_id: forsale_category.id).first_or_create(name: 'tools', category_id: forsale_category.id)
Subcategory.where(name: 'toys+games', category_id: forsale_category.id).first_or_create(name: 'toys+games', category_id: forsale_category.id)
Subcategory.where(name: 'video gaming', category_id: forsale_category.id).first_or_create(name: 'video gaming', category_id: forsale_category.id)
Subcategory.where(name: 'wanted', category_id: forsale_category.id).first_or_create(name: 'wanted', category_id: forsale_category.id)

Subcategory.where(name: 'computer', category_id: gigs_category.id).first_or_create(name: 'computer', category_id: gigs_category.id)
Subcategory.where(name: 'creative', category_id: gigs_category.id).first_or_create(name: 'creative', category_id: gigs_category.id)
Subcategory.where(name: 'crew', category_id: gigs_category.id).first_or_create(name: 'crew', category_id: gigs_category.id)
Subcategory.where(name: 'domestic', category_id: gigs_category.id).first_or_create(name: 'domestic', category_id: gigs_category.id)
Subcategory.where(name: 'event', category_id: gigs_category.id).first_or_create(name: 'event', category_id: gigs_category.id)
Subcategory.where(name: 'labor', category_id: gigs_category.id).first_or_create(name: 'labor', category_id: gigs_category.id)
Subcategory.where(name: 'talent', category_id: gigs_category.id).first_or_create(name: 'talent', category_id: gigs_category.id)
Subcategory.where(name: 'writing', category_id: gigs_category.id).first_or_create(name: 'writing', category_id: gigs_category.id)

Subcategory.where(name: 'strictly platonic', category_id: personals_category.id).first_or_create(name: 'strictly platonic', category_id: personals_category.id)
Subcategory.where(name: 'women seeking women', category_id: personals_category.id).first_or_create(name: 'women seeking women', category_id: personals_category.id)
Subcategory.where(name: 'women seeking men', category_id: personals_category.id).first_or_create(name: 'women seeking men', category_id: personals_category.id)
Subcategory.where(name: 'men seeking women', category_id: personals_category.id).first_or_create(name: 'men seeking women', category_id: personals_category.id)
Subcategory.where(name: 'men seeking men', category_id: personals_category.id).first_or_create(name: 'men seeking men', category_id: personals_category.id)
Subcategory.where(name: 'misc romance', category_id: personals_category.id).first_or_create(name: 'misc romance', category_id: personals_category.id)
Subcategory.where(name: 'casual encounters', category_id: personals_category.id).first_or_create(name: 'casual encounters', category_id: personals_category.id)
Subcategory.where(name: 'missed connections', category_id: personals_category.id).first_or_create(name: 'missed connections', category_id: personals_category.id)
Subcategory.where(name: 'rants and raves', category_id: personals_category.id).first_or_create(name: 'rants and raves', category_id: personals_category.id)



